# The Site Configuration
# Documentation: https://chirpy.cotes.page/posts/getting-started/

title: Jay Shah
tagline: Personal Website
description: >-
  Data Professional with expertise with technology. Hi there! Iâ€™m Jay Shah, and I Turn Data into Actions!

url: "https://jayshah5696.github.io"

author:
  name: Jay Shah
  email: jayshah5696@gmail.com
  twitter: jayjshah

# User Avatar
avatar: /assets/images/Profile.jpg

# Social links
social:
  name: Jay Shah
  links:
    - https://twitter.com/jayjshah
    - https://github.com/jayshah5696
    - https://www.linkedin.com/in/jayshah5696
    - https://huggingface.co/jayshah5696

# Theme settings
theme: jekyll-theme-chirpy

lang: en
timezone: America/Los_Angeles

# Search
search:
  provider: default

# Analytics
analytics:
  google:
    id: 'G-ZQ651N672F'

# Comments
disqus:
  shortname: jayshah5696

# Pagination
paginate: 10

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  - jemoji
  - jekyll-spaceship
  - jekyll-gist
  - jekyll-archives

# Collections
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      author: Jay Shah
  - scope:
      path: "_tabs"
    values:
      layout: page
      comments: false

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
